export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS";
export const UPDATE_INGREDIENTS = "UPDATE_INGREDIENTS";

export const SET_BUN = "ADD_BUN";
export const DELETE_BUN = "DELETE_BUN";